# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 20:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('author', models.CharField(max_length=100, verbose_name='文章作者')),
                ('description', models.CharField(max_length=32, verbose_name='文章描述')),
                ('post_date', models.DateField(verbose_name='发表日期')),
                ('pic', models.ImageField(upload_to='images', verbose_name='图片')),
                ('num', models.IntegerField(verbose_name='阅读次数')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='图片名称')),
                ('src', models.ImageField(upload_to='images', verbose_name='图片链接')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='类型描述')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Type'),
        ),
        migrations.AddField(
            model_name='article',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Type'),
        ),
    ]
