# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20180608_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
